const BirthdayItems = [
  { itemName: "Birthday Cake", price: 800 },
  { itemName: "Birthday Banner", price: 150 },
  { itemName: "Balloons", price: 200 },
  { itemName: "Balloon Pump", price: 100 },
  { itemName: "Balloon Ribbon", price: 50 },
  { itemName: "Fairy Lights", price: 250 },
  { itemName: "Birthday Candles", price: 50 },
  { itemName: "Party Caps", price: 100 },
  { itemName: "Party Poppers", price: 150 },
  { itemName: "Cake Knife", price: 30 },
  { itemName: "Paper Plates", price: 100 },
  { itemName: "Paper Cups", price: 80 },
  { itemName: "Spoons", price: 50 },
  { itemName: "Tissue Paper", price: 50 },
  { itemName: "Cold Drinks", price: 120 },
  { itemName: "Juice", price: 120 },
  { itemName: "Drinking Water", price: 15 },
  { itemName: "Garbage Bags", price: 50 },
  { itemName: "Party Poppers", price: 150 },
];

const newYearPartyItems = [
  { itemName: "New Year Banner", price: 150 },
  { itemName: "Balloons", price: 200 },
  { itemName: "Metallic Balloons", price: 250 },
  { itemName: "Fairy Lights", price: 300 },
  { itemName: "LED Strip Lights", price: 350 },
  { itemName: "Confetti", price: 100 },
  { itemName: "Party Poppers", price: 150 },
  { itemName: "Balloon Ribbon", price: 50 },
  { itemName: "Table Decoration", price: 200 },
  { itemName: "Photo Booth Props", price: 250 },
  { itemName: "Party Hats", price: 100 },
  { itemName: "2027 Glasses", price: 150 },
  { itemName: "Whistles", price: 80 },
  { itemName: "Cold Drink", price: 120 },
  { itemName: "Fruit Juice", price: 120 },
  { itemName: "Mocktail", price: 350 },
  { itemName: "Mineral Water", price: 15 },
  { itemName: "Soda", price: 60 },
  { itemName: "Paper Plates", price: 100 },
  { itemName: "Paper Bowls", price: 80 },
  { itemName: "Paper Cups", price: 80 },
  { itemName: "Spoons", price: 50 },
  { itemName: "Forks", price: 50 },
  { itemName: "Tissue Paper", price: 50 },
  { itemName: "Toothpicks", price: 30 },
  { itemName: "Garbage Bags", price: 60 },
];

const chhathPujaItems = [
  { itemName: "Thekua", price: 20, image: "/images/puja/thekua.webp" },
  { itemName: "Jaggery", price: 80, image: "/images/puja/jaggery.webp" },
  { itemName: "Rice", price: 70, image: "/images/puja/rice.webp" },
  { itemName: "Wheat", price: 60, image: "/images/puja/wheat.webp" },
  {
    itemName: "Wheat Flour",
    price: 60,
    image: "/images/puja/wheat-flour.webp",
  },
  { itemName: "Ghee", price: 250, image: "/images/puja/ghee.webp" },
  { itemName: "Chana Dal", price: 100, image: "/images/puja/chana-dal.webp" },
  { itemName: "Milk", price: 70, image: "/images/puja/milk.webp" },
  { itemName: "Banana", price: 60, image: "/images/puja/banana.webp" },
  { itemName: "Coconut", price: 50, image: "/images/puja/coconut.webp" },
  { itemName: "Sugarcane", price: 80, image: "/images/puja/sugarcane.webp" },
  { itemName: "Apple", price: 150, image: "/images/puja/apple.webp" },
  { itemName: "Orange", price: 100, image: "/images/puja/orange.webp" },
  { itemName: "Guava", price: 80, image: "/images/puja/guava.webp" },
  {
    itemName: "Pomegranate",
    price: 150,
    image: "/images/puja/pomegranate.webp",
  },
  { itemName: "Grapes", price: 120, image: "/images/puja/grapes.webp" },
  { itemName: "Pineapple", price: 100, image: "/images/puja/pineapple.webp" },
  { itemName: "Lemon", price: 50, image: "/images/puja/lemon.webp" },
  {
    itemName: "Sweet Potato",
    price: 80,
    image: "/images/puja/sweet-potato.webp",
  },
  { itemName: "Radish", price: 50, image: "/images/puja/radish.webp" },
  { itemName: "Ginger", price: 60, image: "/images/puja/ginger.webp" },
  {
    itemName: "Fresh Turmeric",
    price: 70,
    image: "/images/puja/fresh-turmeric.webp",
  },
  {
    itemName: "Water Chestnut",
    price: 80,
    image: "/images/puja/water-chestnut.webp",
  },
  { itemName: "Suthni", price: 80, image: "/images/puja/suthni.webp" },
  {
    itemName: "Custard Apple",
    price: 100,
    image: "/images/puja/custard-apple.webp",
  },
  {
    itemName: "Betel Leaves",
    price: 50,
    image: "/images/puja/betel-leaves.webp",
  },
  { itemName: "Betel Nut", price: 80, image: "/images/puja/betel-nut.webp" },
  { itemName: "Cloves", price: 100, image: "/images/puja/cloves.webp" },
  { itemName: "Cardamom", price: 150, image: "/images/puja/cardamom.webp" },
  { itemName: "Raisins", price: 180, image: "/images/puja/raisins.webp" },
  { itemName: "Almonds", price: 300, image: "/images/puja/almonds.webp" },
  { itemName: "Cashews", price: 350, image: "/images/puja/cashews.webp" },
  { itemName: "Fox Nuts", price: 250, image: "/images/puja/fox-nuts.webp" },
  {
    itemName: "Bamboo Soop",
    price: 150,
    image: "/images/puja/bamboo-soop.webp",
  },
  {
    itemName: "Bamboo Daura",
    price: 250,
    image: "/images/puja/bamboo-daura.webp",
  },
  {
    itemName: "Bamboo Basket",
    price: 200,
    image: "/images/puja/bamboo-basket.webp",
  },
  { itemName: "Puja Thali", price: 200, image: "/images/puja/puja-thali.webp" },
  { itemName: "Kalash", price: 100, image: "/images/puja/kalash.webp" },
  {
    itemName: "Mango Leaves",
    price: 50,
    image: "/images/puja/mango-leaves.webp",
  },
  { itemName: "Puja Cloth", price: 150, image: "/images/puja/puja-cloth.webp" },
  { itemName: "Sindoor", price: 30, image: "/images/puja/sindoor.webp" },
  { itemName: "Roli", price: 30, image: "/images/puja/roli.webp" },
  {
    itemName: "Sacred Thread",
    price: 30,
    image: "/images/puja/sacred-thread.webp",
  },
  { itemName: "Gangajal", price: 50, image: "/images/puja/gangajal.webp" },
  { itemName: "Camphor", price: 50, image: "/images/puja/camphor.webp" },
  {
    itemName: "Incense Sticks",
    price: 50,
    image: "/images/puja/incense-sticks.webp",
  },
  { itemName: "Diya", price: 50, image: "/images/puja/diya.webp" },
  {
    itemName: "Cotton Wicks",
    price: 40,
    image: "/images/puja/cotton-wicks.webp",
  },
  {
    itemName: "Mustard Oil",
    price: 150,
    image: "/images/puja/mustard-oil.webp",
  },
  { itemName: "Clay Stove", price: 150, image: "/images/puja/clay-stove.webp" },
];

const christmasItems = [
  { itemName: "Christmas Cake", price: 500 },
  { itemName: "Plum Cake", price: 450 },
  { itemName: "Chocolate Cake", price: 600 },
  { itemName: "Christmas Cookies", price: 250 },
  { itemName: "Chocolates", price: 200 },
  { itemName: "Candy", price: 100 },
  { itemName: "Gingerbread Cookies", price: 250 },
  { itemName: "Christmas Tree", price: 800 },
  { itemName: "Christmas Tree Stand", price: 250 },
  { itemName: "Christmas Star", price: 150 },
  { itemName: "Christmas Lights", price: 300 },
  { itemName: "Christmas Garland", price: 200 },
  { itemName: "Christmas Ornaments", price: 250 },
  { itemName: "Christmas Balls", price: 200 },
  { itemName: "Christmas Stockings", price: 150 },
  { itemName: "Christmas Wreath", price: 300 },
  { itemName: "Santa Claus Cap", price: 80 },
  { itemName: "Santa Claus Mask", price: 100 },
  { itemName: "Santa Costume", price: 500 },
  { itemName: "Reindeer Headband", price: 120 },
  { itemName: "Gift Wrapping Paper", price: 80 },
  { itemName: "Gift Box", price: 150 },
  { itemName: "Gift Ribbon", price: 50 },
  { itemName: "Christmas Gift Bag", price: 100 },
  { itemName: "Christmas Greeting Card", price: 50 },
  { itemName: "Party Balloons", price: 150 },
  { itemName: "Christmas Balloons", price: 200 },
  { itemName: "Party Poppers", price: 150 },
  { itemName: "Confetti", price: 100 },
  { itemName: "Christmas Photo Props", price: 200 },
  { itemName: "Cold Drink", price: 120 },
  { itemName: "Fruit Juice", price: 120 },
  { itemName: "Paper Plates", price: 100 },
  { itemName: "Paper Cups", price: 80 },
  { itemName: "Spoons", price: 50 },
  { itemName: "Forks", price: 50 },
  { itemName: "Tissue Paper", price: 50 },
  { itemName: "Garbage Bags", price: 60 },
];

const diwaliItems = [
  { itemName: "Diyas", price: 100 },
  { itemName: "Clay Diyas", price: 80 },
  { itemName: "Decorative Diyas", price: 200 },
  { itemName: "Cotton Wicks", price: 40 },
  { itemName: "Mustard Oil", price: 150 },
  { itemName: "Ghee", price: 250 },
  { itemName: "Camphor", price: 50 },
  { itemName: "Incense Sticks", price: 50 },
  { itemName: "Rangoli Colors", price: 100 },
  { itemName: "Rangoli Stencils", price: 150 },
  { itemName: "Flower Garland", price: 100 },
  { itemName: "Marigold Flowers", price: 100 },
  { itemName: "Fairy Lights", price: 300 },
  { itemName: "Decorative Lights", price: 250 },
  { itemName: "Diwali Toran", price: 200 },
  { itemName: "Lakshmi Ganesh Idol", price: 300 },
  { itemName: "Puja Thali", price: 200 },
  { itemName: "Kumkum", price: 40 },
  { itemName: "Rice", price: 70 },
  { itemName: "Coconut", price: 50 },
  { itemName: "Betel Leaves", price: 50 },
  { itemName: "Betel Nut", price: 80 },
  { itemName: "Som Papri", price: 200 },
  { itemName: "Kaju Katli", price: 600 },
  { itemName: "Diwali Gift Box", price: 300 },
  { itemName: "Gift Wrapping Paper", price: 80 },
  { itemName: "Decorative Gift Box", price: 150 },
  { itemName: "Party Poppers", price: 150 },
];

const durgaPujaItems = [
  {
    itemName: "Durga Idol",
    price: 1500,
    image: "/images/puja/durga-idol.webp",
  },
  { itemName: "Flowers", price: 100, image: "/images/puja/flowers.webp" },
  {
    itemName: "Marigold Flowers",
    price: 100,
    image: "/images/puja/marigold.webp",
  },
  { itemName: "Lotus Flower", price: 100, image: "/images/puja/lotus.webp" },
  {
    itemName: "Hibiscus Flowers",
    price: 150,
    image: "/images/puja/hibiscus.webp",
  },
  {
    itemName: "Flower Garland",
    price: 150,
    image: "/images/puja/flower-garland.webp",
  },
  { itemName: "Bel Leaves", price: 50, image: "/images/puja/bel-leaves.webp" },
  { itemName: "Coconut", price: 50, image: "/images/puja/coconut.webp" },
  { itemName: "Banana", price: 60, image: "/images/puja/banana.webp" },
  { itemName: "Apple", price: 150, image: "/images/puja/apple.webp" },
  { itemName: "Orange", price: 100, image: "/images/puja/orange.webp" },
  { itemName: "Guava", price: 80, image: "/images/puja/guava.webp" },
  {
    itemName: "Pomegranate",
    price: 150,
    image: "/images/puja/pomegranate.webp",
  },
  { itemName: "Sugarcane", price: 80, image: "/images/puja/sugarcane.webp" },
  { itemName: "Rice", price: 70, image: "/images/puja/rice.webp" },
  { itemName: "Wheat", price: 60, image: "/images/puja/wheat.webp" },
  { itemName: "Lentils", price: 100, image: "/images/puja/lentils.webp" },
  { itemName: "Milk", price: 70, image: "/images/puja/milk.webp" },
  { itemName: "Honey", price: 150, image: "/images/puja/honey.webp" },
  { itemName: "Ghee", price: 250, image: "/images/puja/ghee.webp" },
  { itemName: "Jaggery", price: 80, image: "/images/puja/jaggery.webp" },
  {
    itemName: "Betel Leaves",
    price: 50,
    image: "/images/puja/betel-leaves.webp",
  },
  { itemName: "Betel Nut", price: 80, image: "/images/puja/betel-nut.webp" },
  { itemName: "Kumkum", price: 40, image: "/images/puja/kumkum.webp" },
  { itemName: "Sindoor", price: 30, image: "/images/puja/sindoor.webp" },
  { itemName: "Turmeric", price: 50, image: "/images/puja/turmeric.webp" },
  { itemName: "Akshat Rice", price: 50, image: "/images/puja/akshat.webp" },
  {
    itemName: "Sandalwood Paste",
    price: 100,
    image: "/images/puja/sandalwood-paste.webp",
  },
  {
    itemName: "Incense Sticks",
    price: 50,
    image: "/images/puja/incense-sticks.webp",
  },
  { itemName: "Dhoop", price: 60, image: "/images/puja/dhoop.webp" },
  { itemName: "Camphor", price: 50, image: "/images/puja/camphor.webp" },
  {
    itemName: "Cotton Wicks",
    price: 40,
    image: "/images/puja/cotton-wicks.webp",
  },
  { itemName: "Diya", price: 100, image: "/images/puja/diya.webp" },
  { itemName: "Kalash", price: 100, image: "/images/puja/kalash.webp" },
  {
    itemName: "Mango Leaves",
    price: 50,
    image: "/images/puja/mango-leaves.webp",
  },
  { itemName: "Puja Thali", price: 200, image: "/images/puja/puja-thali.webp" },
  { itemName: "Puja Cloth", price: 150, image: "/images/puja/puja-cloth.webp" },
  {
    itemName: "Conch Shell",
    price: 300,
    image: "/images/puja/conch-shell.webp",
  },
  { itemName: "Puja Bell", price: 250, image: "/images/puja/puja-bell.webp" },
  { itemName: "Sweets", price: 400, image: "/images/puja/sweets.webp" },
  {
    itemName: "Bhog Ingredients",
    price: 500,
    image: "/images/puja/bhog-ingredients.webp",
  },
];

const holiItems = [
  { itemName: "Gulal", price: 80, image: "/images/puja/gulal.webp" },
  {
    itemName: "Holi Colors",
    price: 100,
    image: "/images/puja/holi-colors.webp",
  },
  {
    itemName: "Organic Holi Colors",
    price: 150,
    image: "/images/puja/organic-holi-colors.webp",
  },
  { itemName: "Pichkari", price: 200, image: "/images/puja/pichkari.webp" },
  { itemName: "Water Gun", price: 150, image: "/images/puja/water-gun.webp" },
  {
    itemName: "Water Balloons",
    price: 100,
    image: "/images/puja/water-balloons.webp",
  },
  { itemName: "Holi Spray", price: 120, image: "/images/puja/holi-spray.webp" },
  { itemName: "Holi Cap", price: 80, image: "/images/puja/holi-cap.webp" },
  { itemName: "Holi Mask", price: 100, image: "/images/puja/holi-mask.webp" },
  { itemName: "Gujiya", price: 250, image: "/images/puja/gujiya.webp" },
  { itemName: "Thandai", price: 200, image: "/images/puja/thandai.webp" },
  { itemName: "Milk", price: 70, image: "/images/puja/milk.webp" },
  { itemName: "Sugar", price: 50, image: "/images/puja/sugar.webp" },
  { itemName: "Almonds", price: 300, image: "/images/puja/almonds.webp" },
  { itemName: "Cashews", price: 350, image: "/images/puja/cashews.webp" },
  { itemName: "Cardamom", price: 150, image: "/images/puja/cardamom.webp" },
  { itemName: "Saffron", price: 150, image: "/images/puja/saffron.webp" },
  { itemName: "Coconut", price: 50, image: "/images/puja/coconut.webp" },
  { itemName: "Sweets", price: 300, image: "/images/puja/sweets.webp" },
  { itemName: "Snacks", price: 200, image: "/images/puja/snacks.webp" },
  {
    itemName: "Paper Plates",
    price: 100,
    image: "/images/puja/paper-plates.webp",
  },
  { itemName: "Paper Cups", price: 80, image: "/images/puja/paper-cups.webp" },
  {
    itemName: "Tissue Paper",
    price: 50,
    image: "/images/puja/tissue-paper.webp",
  },
];

const jagaddhatriPujaItems = [
  {
    itemName: "Jagaddhatri Idol",
    price: 1500,
    image: "/images/puja/jagaddhatri-idol.webp",
  },
  { itemName: "Flowers", price: 100, image: "/images/puja/flowers.webp" },
  {
    itemName: "Marigold Flowers",
    price: 100,
    image: "/images/puja/marigold.webp",
  },
  { itemName: "Lotus Flower", price: 100, image: "/images/puja/lotus.webp" },
  {
    itemName: "Hibiscus Flowers",
    price: 150,
    image: "/images/puja/hibiscus.webp",
  },
  {
    itemName: "Flower Garland",
    price: 150,
    image: "/images/puja/flower-garland.webp",
  },
  { itemName: "Bel Leaves", price: 50, image: "/images/puja/bel-leaves.webp" },
  { itemName: "Coconut", price: 50, image: "/images/puja/coconut.webp" },
  { itemName: "Banana", price: 60, image: "/images/puja/banana.webp" },
  { itemName: "Apple", price: 150, image: "/images/puja/apple.webp" },
  { itemName: "Orange", price: 100, image: "/images/puja/orange.webp" },
  { itemName: "Guava", price: 80, image: "/images/puja/guava.webp" },
  {
    itemName: "Pomegranate",
    price: 150,
    image: "/images/puja/pomegranate.webp",
  },
  { itemName: "Sugarcane", price: 80, image: "/images/puja/sugarcane.webp" },
  { itemName: "Rice", price: 70, image: "/images/puja/rice.webp" },
  { itemName: "Wheat", price: 60, image: "/images/puja/wheat.webp" },
  { itemName: "Lentils", price: 100, image: "/images/puja/lentils.webp" },
  { itemName: "Milk", price: 70, image: "/images/puja/milk.webp" },
  { itemName: "Honey", price: 150, image: "/images/puja/honey.webp" },
  { itemName: "Ghee", price: 250, image: "/images/puja/ghee.webp" },
  { itemName: "Jaggery", price: 80, image: "/images/puja/jaggery.webp" },
  {
    itemName: "Betel Leaves",
    price: 50,
    image: "/images/puja/betel-leaves.webp",
  },
  { itemName: "Betel Nut", price: 80, image: "/images/puja/betel-nut.webp" },
  { itemName: "Kumkum", price: 40, image: "/images/puja/kumkum.webp" },
  { itemName: "Sindoor", price: 30, image: "/images/puja/sindoor.webp" },
  { itemName: "Turmeric", price: 50, image: "/images/puja/turmeric.webp" },
  { itemName: "Akshat Rice", price: 50, image: "/images/puja/akshat.webp" },
  {
    itemName: "Sandalwood Paste",
    price: 100,
    image: "/images/puja/sandalwood-paste.webp",
  },
  {
    itemName: "Incense Sticks",
    price: 50,
    image: "/images/puja/incense-sticks.webp",
  },
  { itemName: "Dhoop", price: 60, image: "/images/puja/dhoop.webp" },
  { itemName: "Camphor", price: 50, image: "/images/puja/camphor.webp" },
  {
    itemName: "Cotton Wicks",
    price: 40,
    image: "/images/puja/cotton-wicks.webp",
  },
  {
    itemName: "Mustard Oil",
    price: 150,
    image: "/images/puja/mustard-oil.webp",
  },
  { itemName: "Diya", price: 100, image: "/images/puja/diya.webp" },
  { itemName: "Kalash", price: 100, image: "/images/puja/kalash.webp" },
  {
    itemName: "Mango Leaves",
    price: 50,
    image: "/images/puja/mango-leaves.webp",
  },
  { itemName: "Puja Thali", price: 200, image: "/images/puja/puja-thali.webp" },
  { itemName: "Puja Cloth", price: 150, image: "/images/puja/puja-cloth.webp" },
  { itemName: "Puja Bell", price: 250, image: "/images/puja/puja-bell.webp" },
  {
    itemName: "Conch Shell",
    price: 300,
    image: "/images/puja/conch-shell.webp",
  },
  { itemName: "Sweets", price: 400, image: "/images/puja/sweets.webp" },
  {
    itemName: "Bhog Ingredients",
    price: 500,
    image: "/images/puja/bhog-ingredients.webp",
  },
];

const janmashtamiItems = [
  {
    itemName: "Krishna Idol",
    price: 500,
    image: "/images/puja/krishna-idol.webp",
  },
  {
    itemName: "Baby Krishna Idol",
    price: 300,
    image: "/images/puja/baby-krishna.webp",
  },
  { itemName: "Jhula", price: 400, image: "/images/puja/jhula.webp" },
  {
    itemName: "Jhula Decoration",
    price: 200,
    image: "/images/puja/jhula-decoration.webp",
  },
  {
    itemName: "Peacock Feather",
    price: 50,
    image: "/images/puja/peacock-feather.webp",
  },
  {
    itemName: "Krishna Crown",
    price: 150,
    image: "/images/puja/krishna-crown.webp",
  },
  { itemName: "Flute", price: 100, image: "/images/puja/flute.webp" },
  {
    itemName: "Yellow Cloth",
    price: 150,
    image: "/images/puja/yellow-cloth.webp",
  },
  {
    itemName: "Tulsi Leaves",
    price: 30,
    image: "/images/puja/tulsi-leaves.webp",
  },
  { itemName: "Flowers", price: 100, image: "/images/puja/flowers.webp" },
  {
    itemName: "Flower Garland",
    price: 150,
    image: "/images/puja/flower-garland.webp",
  },
  { itemName: "Coconut", price: 50, image: "/images/puja/coconut.webp" },
  { itemName: "Banana", price: 60, image: "/images/puja/banana.webp" },
  { itemName: "Apple", price: 150, image: "/images/puja/apple.webp" },
  { itemName: "Grapes", price: 120, image: "/images/puja/grapes.webp" },
  { itemName: "Mango", price: 150, image: "/images/puja/mango.webp" },
  { itemName: "Milk", price: 70, image: "/images/puja/milk.webp" },
  { itemName: "Curd", price: 80, image: "/images/puja/curd.webp" },
  { itemName: "Butter", price: 100, image: "/images/puja/butter.webp" },
  { itemName: "Ghee", price: 250, image: "/images/puja/ghee.webp" },
  { itemName: "Honey", price: 150, image: "/images/puja/honey.webp" },
  { itemName: "Sugar", price: 50, image: "/images/puja/sugar.webp" },
  { itemName: "Mishri", price: 80, image: "/images/puja/mishri.webp" },
  { itemName: "Makhana", price: 250, image: "/images/puja/makhana.webp" },
  { itemName: "Dry Fruits", price: 300, image: "/images/puja/dry-fruits.webp" },
  {
    itemName: "Panchamrit Ingredients",
    price: 200,
    image: "/images/puja/panchamrit.webp",
  },
  {
    itemName: "Sandalwood Paste",
    price: 100,
    image: "/images/puja/sandalwood-paste.webp",
  },
  {
    itemName: "Incense Sticks",
    price: 50,
    image: "/images/puja/incense-sticks.webp",
  },
  { itemName: "Dhoop", price: 60, image: "/images/puja/dhoop.webp" },
  { itemName: "Camphor", price: 50, image: "/images/puja/camphor.webp" },
  {
    itemName: "Cotton Wicks",
    price: 40,
    image: "/images/puja/cotton-wicks.webp",
  },
  { itemName: "Diya", price: 100, image: "/images/puja/diya.webp" },
  { itemName: "Kalash", price: 100, image: "/images/puja/kalash.webp" },
  {
    itemName: "Mango Leaves",
    price: 50,
    image: "/images/puja/mango-leaves.webp",
  },
  { itemName: "Puja Thali", price: 200, image: "/images/puja/puja-thali.webp" },
  { itemName: "Kumkum", price: 40, image: "/images/puja/kumkum.webp" },
  { itemName: "Turmeric", price: 50, image: "/images/puja/turmeric.webp" },
  {
    itemName: "Betel Leaves",
    price: 50,
    image: "/images/puja/betel-leaves.webp",
  },
  { itemName: "Betel Nut", price: 80, image: "/images/puja/betel-nut.webp" },
  { itemName: "Sweets", price: 400, image: "/images/puja/sweets.webp" },
];

const lakshmiPujaItems = [
  {
    itemName: "Lakshmi Ganesh Idol",
    price: 300,
    image: "/images/puja/lakshmi-ganesh-idol.webp",
  },
  { itemName: "Lotus Flower", price: 100, image: "/images/puja/lotus.webp" },
  {
    itemName: "Marigold Flowers",
    price: 100,
    image: "/images/puja/marigold.webp",
  },
  {
    itemName: "Flower Garland",
    price: 150,
    image: "/images/puja/flower-garland.webp",
  },
  { itemName: "Coconut", price: 50, image: "/images/puja/coconut.webp" },
  { itemName: "Banana", price: 60, image: "/images/puja/banana.webp" },
  { itemName: "Apple", price: 150, image: "/images/puja/apple.webp" },
  { itemName: "Orange", price: 100, image: "/images/puja/orange.webp" },
  { itemName: "Guava", price: 80, image: "/images/puja/guava.webp" },
  {
    itemName: "Pomegranate",
    price: 150,
    image: "/images/puja/pomegranate.webp",
  },
  { itemName: "Sugarcane", price: 80, image: "/images/puja/sugarcane.webp" },
  { itemName: "Rice", price: 70, image: "/images/puja/rice.webp" },
  { itemName: "Wheat", price: 60, image: "/images/puja/wheat.webp" },
  { itemName: "Jaggery", price: 80, image: "/images/puja/jaggery.webp" },
  { itemName: "Ghee", price: 250, image: "/images/puja/ghee.webp" },
  { itemName: "Milk", price: 70, image: "/images/puja/milk.webp" },
  { itemName: "Honey", price: 150, image: "/images/puja/honey.webp" },
  {
    itemName: "Betel Leaves",
    price: 50,
    image: "/images/puja/betel-leaves.webp",
  },
  { itemName: "Betel Nut", price: 80, image: "/images/puja/betel-nut.webp" },
  { itemName: "Kumkum", price: 40, image: "/images/puja/kumkum.webp" },
  { itemName: "Turmeric", price: 50, image: "/images/puja/turmeric.webp" },
  { itemName: "Sindoor", price: 30, image: "/images/puja/sindoor.webp" },
  { itemName: "Akshat Rice", price: 50, image: "/images/puja/akshat.webp" },
  {
    itemName: "Sandalwood Paste",
    price: 100,
    image: "/images/puja/sandalwood-paste.webp",
  },
  {
    itemName: "Incense Sticks",
    price: 50,
    image: "/images/puja/incense-sticks.webp",
  },
  { itemName: "Dhoop", price: 60, image: "/images/puja/dhoop.webp" },
  { itemName: "Camphor", price: 50, image: "/images/puja/camphor.webp" },
  {
    itemName: "Cotton Wicks",
    price: 40,
    image: "/images/puja/cotton-wicks.webp",
  },
  {
    itemName: "Mustard Oil",
    price: 150,
    image: "/images/puja/mustard-oil.webp",
  },
  { itemName: "Diya", price: 100, image: "/images/puja/diya.webp" },
  { itemName: "Clay Diyas", price: 80, image: "/images/puja/clay-diyas.webp" },
  { itemName: "Kalash", price: 100, image: "/images/puja/kalash.webp" },
  {
    itemName: "Mango Leaves",
    price: 50,
    image: "/images/puja/mango-leaves.webp",
  },
  { itemName: "Puja Thali", price: 200, image: "/images/puja/puja-thali.webp" },
  { itemName: "Puja Cloth", price: 150, image: "/images/puja/puja-cloth.webp" },
  { itemName: "Sweets", price: 400, image: "/images/puja/sweets.webp" },
  { itemName: "Kaju Katli", price: 600, image: "/images/puja/kaju-katli.webp" },
  {
    itemName: "Rangoli Colors",
    price: 100,
    image: "/images/puja/rangoli-colors.webp",
  },
  {
    itemName: "Rangoli Stencil",
    price: 150,
    image: "/images/puja/rangoli-stencil.webp",
  },
  { itemName: "Toran", price: 200, image: "/images/puja/toran.webp" },
  {
    itemName: "Decorative Lights",
    price: 250,
    image: "/images/puja/decorative-lights.webp",
  },
];

const saraswatiPujaItems = [
  {
    itemName: "Saraswati Idol",
    price: 500,
    image: "/images/puja/saraswati-idol.webp",
  },
  {
    itemName: "Palash Flowers",
    price: 150,
    image: "/images/puja/palash-flowers.webp",
  },
  {
    itemName: "White Flowers",
    price: 150,
    image: "/images/puja/white-flowers.webp",
  },
  {
    itemName: "Marigold Flowers",
    price: 100,
    image: "/images/puja/marigold.webp",
  },
  {
    itemName: "Flower Garland",
    price: 150,
    image: "/images/puja/flower-garland.webp",
  },
  { itemName: "Lotus Flower", price: 100, image: "/images/puja/lotus.webp" },
  { itemName: "Bel Leaves", price: 50, image: "/images/puja/bel-leaves.webp" },
  { itemName: "Coconut", price: 50, image: "/images/puja/coconut.webp" },
  { itemName: "Banana", price: 60, image: "/images/puja/banana.webp" },
  { itemName: "Apple", price: 150, image: "/images/puja/apple.webp" },
  { itemName: "Orange", price: 100, image: "/images/puja/orange.webp" },
  { itemName: "Guava", price: 80, image: "/images/puja/guava.webp" },
  { itemName: "Sugarcane", price: 80, image: "/images/puja/sugarcane.webp" },
  { itemName: "Rice", price: 70, image: "/images/puja/rice.webp" },
  {
    itemName: "Puffed Rice",
    price: 80,
    image: "/images/puja/puffed-rice.webp",
  },
  { itemName: "Milk", price: 70, image: "/images/puja/milk.webp" },
  { itemName: "Curd", price: 80, image: "/images/puja/curd.webp" },
  { itemName: "Ghee", price: 250, image: "/images/puja/ghee.webp" },
  { itemName: "Honey", price: 150, image: "/images/puja/honey.webp" },
  { itemName: "Jaggery", price: 80, image: "/images/puja/jaggery.webp" },
  {
    itemName: "Betel Leaves",
    price: 50,
    image: "/images/puja/betel-leaves.webp",
  },
  { itemName: "Betel Nut", price: 80, image: "/images/puja/betel-nut.webp" },
  { itemName: "Kumkum", price: 40, image: "/images/puja/kumkum.webp" },
  { itemName: "Turmeric", price: 50, image: "/images/puja/turmeric.webp" },
  { itemName: "Akshat Rice", price: 50, image: "/images/puja/akshat.webp" },
  {
    itemName: "Sandalwood Paste",
    price: 100,
    image: "/images/puja/sandalwood-paste.webp",
  },
  {
    itemName: "Incense Sticks",
    price: 50,
    image: "/images/puja/incense-sticks.webp",
  },
  { itemName: "Dhoop", price: 60, image: "/images/puja/dhoop.webp" },
  { itemName: "Camphor", price: 50, image: "/images/puja/camphor.webp" },
  {
    itemName: "Cotton Wicks",
    price: 40,
    image: "/images/puja/cotton-wicks.webp",
  },
  { itemName: "Diya", price: 100, image: "/images/puja/diya.webp" },
  { itemName: "Kalash", price: 100, image: "/images/puja/kalash.webp" },
  {
    itemName: "Mango Leaves",
    price: 50,
    image: "/images/puja/mango-leaves.webp",
  },
  { itemName: "Puja Thali", price: 200, image: "/images/puja/puja-thali.webp" },
  { itemName: "Puja Cloth", price: 150, image: "/images/puja/puja-cloth.webp" },
  { itemName: "Books", price: 200, image: "/images/puja/books.webp" },
  { itemName: "Notebook", price: 50, image: "/images/puja/notebook.webp" },
  { itemName: "Pen", price: 20, image: "/images/puja/pen.webp" },
  { itemName: "Pencil", price: 20, image: "/images/puja/pencil.webp" },
  {
    itemName: "Drawing Book",
    price: 80,
    image: "/images/puja/drawing-book.webp",
  },
  { itemName: "Sweets", price: 400, image: "/images/puja/sweets.webp" },
  {
    itemName: "Khichuri Ingredients",
    price: 400,
    image: "/images/puja/khichuri.webp",
  },
];

const kaliPujaItems = [
  { itemName: "Kali Idol", price: 1000, image: "/images/puja/kali-idol.webp" },
  {
    itemName: "Red Hibiscus Flowers",
    price: 150,
    image: "/images/puja/hibiscus.webp",
  },
  {
    itemName: "Marigold Flowers",
    price: 100,
    image: "/images/puja/marigold.webp",
  },
  {
    itemName: "Flower Garland",
    price: 150,
    image: "/images/puja/flower-garland.webp",
  },
  { itemName: "Bel Leaves", price: 50, image: "/images/puja/bel-leaves.webp" },
  { itemName: "Coconut", price: 50, image: "/images/puja/coconut.webp" },
  { itemName: "Banana", price: 60, image: "/images/puja/banana.webp" },
  { itemName: "Apple", price: 150, image: "/images/puja/apple.webp" },
  { itemName: "Orange", price: 100, image: "/images/puja/orange.webp" },
  {
    itemName: "Pomegranate",
    price: 150,
    image: "/images/puja/pomegranate.webp",
  },
  { itemName: "Sugarcane", price: 80, image: "/images/puja/sugarcane.webp" },
  { itemName: "Rice", price: 70, image: "/images/puja/rice.webp" },
  { itemName: "Wheat", price: 60, image: "/images/puja/wheat.webp" },
  { itemName: "Lentils", price: 100, image: "/images/puja/lentils.webp" },
  { itemName: "Jaggery", price: 80, image: "/images/puja/jaggery.webp" },
  { itemName: "Milk", price: 70, image: "/images/puja/milk.webp" },
  { itemName: "Ghee", price: 250, image: "/images/puja/ghee.webp" },
  { itemName: "Honey", price: 150, image: "/images/puja/honey.webp" },
  {
    itemName: "Betel Leaves",
    price: 50,
    image: "/images/puja/betel-leaves.webp",
  },
  { itemName: "Betel Nut", price: 80, image: "/images/puja/betel-nut.webp" },
  { itemName: "Kumkum", price: 40, image: "/images/puja/kumkum.webp" },
  { itemName: "Sindoor", price: 30, image: "/images/puja/sindoor.webp" },
  { itemName: "Turmeric", price: 50, image: "/images/puja/turmeric.webp" },
  { itemName: "Akshat Rice", price: 50, image: "/images/puja/akshat.webp" },
  {
    itemName: "Sandalwood Paste",
    price: 100,
    image: "/images/puja/sandalwood-paste.webp",
  },
  {
    itemName: "Incense Sticks",
    price: 50,
    image: "/images/puja/incense-sticks.webp",
  },
  { itemName: "Dhoop", price: 60, image: "/images/puja/dhoop.webp" },
  { itemName: "Camphor", price: 50, image: "/images/puja/camphor.webp" },
  {
    itemName: "Cotton Wicks",
    price: 40,
    image: "/images/puja/cotton-wicks.webp",
  },
  {
    itemName: "Mustard Oil",
    price: 150,
    image: "/images/puja/mustard-oil.webp",
  },
  { itemName: "Diya", price: 100, image: "/images/puja/diya.webp" },
  { itemName: "Clay Lamps", price: 100, image: "/images/puja/clay-lamps.webp" },
  { itemName: "Kalash", price: 100, image: "/images/puja/kalash.webp" },
  {
    itemName: "Mango Leaves",
    price: 50,
    image: "/images/puja/mango-leaves.webp",
  },
  { itemName: "Puja Thali", price: 200, image: "/images/puja/puja-thali.webp" },
  { itemName: "Puja Cloth", price: 150, image: "/images/puja/puja-cloth.webp" },
  { itemName: "Red Cloth", price: 100, image: "/images/puja/red-cloth.webp" },
  { itemName: "Puja Bell", price: 250, image: "/images/puja/puja-bell.webp" },
  {
    itemName: "Conch Shell",
    price: 300,
    image: "/images/puja/conch-shell.webp",
  },
  { itemName: "Sweets", price: 400, image: "/images/puja/sweets.webp" },
  { itemName: "Dry Fruits", price: 300, image: "/images/puja/dry-fruits.webp" },
];

const poilaBoishakhItems = [
  {
    itemName: "Bengali New Year Banner",
    price: 150,
    image: "/images/puja/bengali-new-year-banner.webp",
  },
  {
    itemName: "New Year Greeting Card",
    price: 50,
    image: "/images/puja/greeting-card.webp",
  },
  { itemName: "Flowers", price: 100, image: "/images/puja/flowers.webp" },
  {
    itemName: "Flower Garland",
    price: 150,
    image: "/images/puja/flower-garland.webp",
  },
  {
    itemName: "Marigold Flowers",
    price: 100,
    image: "/images/puja/marigold.webp",
  },
  { itemName: "Lotus Flower", price: 100, image: "/images/puja/lotus.webp" },
  { itemName: "Coconut", price: 50, image: "/images/puja/coconut.webp" },
  { itemName: "Banana", price: 60, image: "/images/puja/banana.webp" },
  { itemName: "Apple", price: 150, image: "/images/puja/apple.webp" },
  { itemName: "Orange", price: 100, image: "/images/puja/orange.webp" },
  { itemName: "Mango", price: 150, image: "/images/puja/mango.webp" },
  {
    itemName: "Pomegranate",
    price: 150,
    image: "/images/puja/pomegranate.webp",
  },
  {
    itemName: "Betel Leaves",
    price: 50,
    image: "/images/puja/betel-leaves.webp",
  },
  { itemName: "Betel Nut", price: 80, image: "/images/puja/betel-nut.webp" },
  { itemName: "Rice", price: 70, image: "/images/puja/rice.webp" },
  { itemName: "Jaggery", price: 80, image: "/images/puja/jaggery.webp" },
  { itemName: "Milk", price: 70, image: "/images/puja/milk.webp" },
  { itemName: "Ghee", price: 250, image: "/images/puja/ghee.webp" },
  { itemName: "Curd", price: 80, image: "/images/puja/curd.webp" },
  { itemName: "Sandesh", price: 300, image: "/images/puja/sandesh.webp" },
  { itemName: "Rasgulla", price: 250, image: "/images/puja/rasgulla.webp" },
  { itemName: "Mishti Doi", price: 200, image: "/images/puja/mishti-doi.webp" },
  { itemName: "Sweets", price: 400, image: "/images/puja/sweets.webp" },
  { itemName: "Panta Rice", price: 150, image: "/images/puja/panta-rice.webp" },
  { itemName: "Fish", price: 400, image: "/images/puja/fish.webp" },
  {
    itemName: "New Clothes",
    price: 500,
    image: "/images/puja/new-clothes.webp",
  },
  {
    itemName: "Bengali Calendar",
    price: 100,
    image: "/images/puja/bengali-calendar.webp",
  },
  { itemName: "Puja Thali", price: 200, image: "/images/puja/puja-thali.webp" },
  {
    itemName: "Incense Sticks",
    price: 50,
    image: "/images/puja/incense-sticks.webp",
  },
  { itemName: "Camphor", price: 50, image: "/images/puja/camphor.webp" },
  {
    itemName: "Cotton Wicks",
    price: 40,
    image: "/images/puja/cotton-wicks.webp",
  },
  { itemName: "Diya", price: 100, image: "/images/puja/diya.webp" },
  {
    itemName: "Decorative Lights",
    price: 300,
    image: "/images/puja/decorative-lights.webp",
  },
  {
    itemName: "Rangoli Colors",
    price: 100,
    image: "/images/puja/rangoli-colors.webp",
  },
  {
    itemName: "Alpana Powder",
    price: 100,
    image: "/images/puja/alpana-powder.webp",
  },
  { itemName: "Gift Box", price: 200, image: "/images/puja/gift-box.webp" },
];

const marriageAnniversaryItems = [
  { itemName: "Anniversary Cake", price: 700 },
  { itemName: "Chocolate Cake", price: 600 },
  { itemName: "Flowers", price: 200 },
  { itemName: "Rose Bouquet", price: 300 },
  { itemName: "Flower Garland", price: 200 },
  { itemName: "Rose Petals", price: 150 },
  { itemName: "Decorative Balloons", price: 200 },
  { itemName: "Heart Balloons", price: 150 },
  { itemName: "Anniversary Banner", price: 150 },
  { itemName: "Fairy Lights", price: 300 },
  { itemName: "LED Candles", price: 200 },
  { itemName: "Scented Candles", price: 250 },
  { itemName: "Table Decoration", price: 250 },
  { itemName: "Photo Frame", price: 250 },
  { itemName: "Couple Photo Frame", price: 400 },
  { itemName: "Photo Album", price: 500 },
  { itemName: "Greeting Card", price: 80 },
  { itemName: "Anniversary Gift Box", price: 300 },
  { itemName: "Chocolate Box", price: 300 },
  { itemName: "Dry Fruits Gift Box", price: 500 },
  { itemName: "Perfume", price: 500 },
  { itemName: "Couple Mug Set", price: 300 },
  { itemName: "Wine Glass Set", price: 500 },
  { itemName: "Dinner Set", price: 800 },
  { itemName: "Artificial Rose", price: 100 },
  { itemName: "Gift Wrapping Paper", price: 80 },
  { itemName: "Gift Ribbon", price: 50 },
  { itemName: "Party Poppers", price: 150 },
  { itemName: "Confetti", price: 100 },
  { itemName: "Photo Booth Props", price: 200 },
  { itemName: "Sweets", price: 300 },
  { itemName: "Ice Cream", price: 300 },
  { itemName: "Pizza", price: 400 },
  { itemName: "Burger", price: 250 },
  { itemName: "French Fries", price: 180 },
  { itemName: "Pasta", price: 300 },
  { itemName: "Cold Drink", price: 100 },
  { itemName: "Fruit Juice", price: 150 },
  { itemName: "Mocktail", price: 250 },
  { itemName: "Paper Plates", price: 100 },
  { itemName: "Paper Cups", price: 80 },
  { itemName: "Spoons", price: 50 },
  { itemName: "Forks", price: 50 },
  { itemName: "Tissue Paper", price: 50 },
];
